//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zootype.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zootype.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn {
            get {
                object obj = ResourceManager.GetObject("btn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn2 {
            get {
                object obj = ResourceManager.GetObject("btn2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap F11 {
            get {
                object obj = ResourceManager.GetObject("F11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap F12 {
            get {
                object obj = ResourceManager.GetObject("F12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap F13 {
            get {
                object obj = ResourceManager.GetObject("F13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap F21 {
            get {
                object obj = ResourceManager.GetObject("F21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap F22 {
            get {
                object obj = ResourceManager.GetObject("F22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap F23 {
            get {
                object obj = ResourceManager.GetObject("F23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap F31 {
            get {
                object obj = ResourceManager.GetObject("F31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap F32 {
            get {
                object obj = ResourceManager.GetObject("F32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap F33 {
            get {
                object obj = ResourceManager.GetObject("F33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T01 {
            get {
                object obj = ResourceManager.GetObject("T01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He is a good swimmer and we can see him outside his hole during the day looking for something to eat..
        /// </summary>
        internal static string T011 {
            get {
                return ResourceManager.GetString("T011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T02 {
            get {
                object obj = ResourceManager.GetObject("T02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to these fish are very small in size. We can find them on coral reefs swimming in tropical and subtropical waters...
        /// </summary>
        internal static string T021 {
            get {
                return ResourceManager.GetString("T021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T03 {
            get {
                object obj = ResourceManager.GetObject("T03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the wild, this species commonly inhabits the homes of pistol shrimp, but does not appear to interact. They like to be in pairs..
        /// </summary>
        internal static string T031 {
            get {
                return ResourceManager.GetString("T031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T04 {
            get {
                object obj = ResourceManager.GetObject("T04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They are large, gray marine mammals with bodies that taper into a flat surface, with a spoon-shaped tail..
        /// </summary>
        internal static string T041 {
            get {
                return ResourceManager.GetString("T041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T05 {
            get {
                object obj = ResourceManager.GetObject("T05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It inhabits areas with coral reefs, at depths of up to more than 30 meters, using some corals as a refuge against predators..
        /// </summary>
        internal static string T051 {
            get {
                return ResourceManager.GetString("T051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T06 {
            get {
                object obj = ResourceManager.GetObject("T06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They are flatworms that live under rocks in the littoral region. This worm feeds on algae attached to the rock..
        /// </summary>
        internal static string T061 {
            get {
                return ResourceManager.GetString("T061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T07 {
            get {
                object obj = ResourceManager.GetObject("T07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is characterized by having a very large mouth, and very sharp pointed teeth, some of these teeth are inclined backwards, so that their prey do not get loose easily..
        /// </summary>
        internal static string T071 {
            get {
                return ResourceManager.GetString("T071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T08 {
            get {
                object obj = ResourceManager.GetObject("T08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They are excellent swimmers. They usually live in slow-flowing rivers and feed on a wide variety of animals, preferably live ones..
        /// </summary>
        internal static string T081 {
            get {
                return ResourceManager.GetString("T081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T09 {
            get {
                object obj = ResourceManager.GetObject("T09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It usually has stripes on the pectoral fins of varying sizes, thickness and shapes, with quite remarkable black and white antennae, without tissues on the dorsal fins..
        /// </summary>
        internal static string T091 {
            get {
                return ResourceManager.GetString("T091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T10 {
            get {
                object obj = ResourceManager.GetObject("T10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They are easily identifiable by their huge heads and prominent rounded foreheads. They have the largest brain of all known creatures that have populated the Earth..
        /// </summary>
        internal static string T101 {
            get {
                return ResourceManager.GetString("T101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T11 {
            get {
                object obj = ResourceManager.GetObject("T11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They tend to concentrate where major ocean currents meet. They live in surface waters where the temperature exceeds 15 ° C..
        /// </summary>
        internal static string T111 {
            get {
                return ResourceManager.GetString("T111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T12 {
            get {
                object obj = ResourceManager.GetObject("T12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is found in the temperate waters of all oceans and is considered one of the largest fish in the world..
        /// </summary>
        internal static string T121 {
            get {
                return ResourceManager.GetString("T121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T13 {
            get {
                object obj = ResourceManager.GetObject("T13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal about 5m tall, yellowish coat full of orange spots, very long and slender neck, small head, short horns covered by the skin..
        /// </summary>
        internal static string T131 {
            get {
                return ResourceManager.GetString("T131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T14 {
            get {
                object obj = ResourceManager.GetObject("T14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal with a slender body, strong and rough hair, a narrow head and a short tail; it is very agile and fast, and climbs with ease over rugged terrain..
        /// </summary>
        internal static string T141 {
            get {
                return ResourceManager.GetString("T141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T15 {
            get {
                object obj = ResourceManager.GetObject("T15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal smaller than the horse, with short white or yellowish hair, with brown or black stripes.
        /// </summary>
        internal static string T151 {
            get {
                return ResourceManager.GetString("T151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T16 {
            get {
                object obj = ResourceManager.GetObject("T16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small head animal, long ears, highly developed hind legs, which it uses to move in great jumps, and a long and robust tail on which it leans when standing..
        /// </summary>
        internal static string T161 {
            get {
                return ResourceManager.GetString("T161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T17 {
            get {
                object obj = ResourceManager.GetObject("T17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal about 50 cm long, generally reddish or gray fur, very strong hind legs and larger than the front ones, and a long and very bushy tail, which often bends over its body up to the head..
        /// </summary>
        internal static string T171 {
            get {
                return ResourceManager.GetString("T171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T18 {
            get {
                object obj = ResourceManager.GetObject("T18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large animal, the largest of the terrestrial ones, with dark gray, thick, rough and hairless skin, large hanging ears, long prehensile trunk..
        /// </summary>
        internal static string T181 {
            get {
                return ResourceManager.GetString("T181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T19 {
            get {
                object obj = ResourceManager.GetObject("T19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They tend to concentrate where major ocean currents meet. They live in surface waters where the temperature exceeds 15 ° C..
        /// </summary>
        internal static string T191 {
            get {
                return ResourceManager.GetString("T191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T20 {
            get {
                object obj = ResourceManager.GetObject("T20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a carnivorous mammal of the canine family, which is a subspecies of the wolf but is domesticated..
        /// </summary>
        internal static string T201 {
            get {
                return ResourceManager.GetString("T201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T21 {
            get {
                object obj = ResourceManager.GetObject("T21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They are carnivorous mammals of the feline family, more social despite being the most feared and known predators..
        /// </summary>
        internal static string T211 {
            get {
                return ResourceManager.GetString("T211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T22 {
            get {
                object obj = ResourceManager.GetObject("T22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A carnivorous animal little larger than a cat and with gray fur, it is characterized by spots on the eyes that make it look like it has a mask..
        /// </summary>
        internal static string T221 {
            get {
                return ResourceManager.GetString("T221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T23 {
            get {
                object obj = ResourceManager.GetObject("T23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a reptile of the boa family, being the largest snake in the world..
        /// </summary>
        internal static string T231 {
            get {
                return ResourceManager.GetString("T231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T24 {
            get {
                object obj = ResourceManager.GetObject("T24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the largest lizard in the world, they can measure 2 to 3 meters and weigh 70kg. Due to their size they are super predators in their ecosystems, although they are mainly scavengers..
        /// </summary>
        internal static string T241 {
            get {
                return ResourceManager.GetString("T241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T25 {
            get {
                object obj = ResourceManager.GetObject("T25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large, plump bird found around the edges of slow-moving lakes and streams. The head seems too small for its large brown body.
        /// </summary>
        internal static string T251 {
            get {
                return ResourceManager.GetString("T251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T26 {
            get {
                object obj = ResourceManager.GetObject("T26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny cockatoo with a long pointed tail. When perched, the yellowish face and crest and orange cheek patch of the male are distinctive..
        /// </summary>
        internal static string T261 {
            get {
                return ResourceManager.GetString("T261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T27 {
            get {
                object obj = ResourceManager.GetObject("T27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The moth often has feather-like antennae without a stick at the end. When perched, their wings are flat. They tend to have thick-furry bodies and more earthy colored wings..
        /// </summary>
        internal static string T271 {
            get {
                return ResourceManager.GetString("T271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T28 {
            get {
                object obj = ResourceManager.GetObject("T28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It begins its life as a caterpillar, which is wrapped in a silk thread and later emerges as a butterfly with colorful wings..
        /// </summary>
        internal static string T281 {
            get {
                return ResourceManager.GetString("T281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T29 {
            get {
                object obj = ResourceManager.GetObject("T29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bumblebee is a large type of insect, hairy and close relatives of the well-known bee..
        /// </summary>
        internal static string T291 {
            get {
                return ResourceManager.GetString("T291", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T30 {
            get {
                object obj = ResourceManager.GetObject("T30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a small bird. There is no other bird that sings so deeply, so full of ecstasy as the nightingale. The melody is infinitely varied..
        /// </summary>
        internal static string T301 {
            get {
                return ResourceManager.GetString("T301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T31 {
            get {
                object obj = ResourceManager.GetObject("T31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has yellow legs and a long bill of the same color that serves as its main hunting and defense tool..
        /// </summary>
        internal static string T311 {
            get {
                return ResourceManager.GetString("T311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T32 {
            get {
                object obj = ResourceManager.GetObject("T32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is characterized by its glossy black plumage, its throat feathers are hard, its beak is very strong and also black. The tail is elongated and wedge-shaped.
        ///.
        /// </summary>
        internal static string T321 {
            get {
                return ResourceManager.GetString("T321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T33 {
            get {
                object obj = ResourceManager.GetObject("T33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most common place to find owls are in forest areas.
        ///They are territorial and do not hesitate to make it notice to unexpected visitors.
        ///
        ///.
        /// </summary>
        internal static string T331 {
            get {
                return ResourceManager.GetString("T331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T34 {
            get {
                object obj = ResourceManager.GetObject("T34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the largest bird on the American continent and is among the largest raptors in the world..
        /// </summary>
        internal static string T341 {
            get {
                return ResourceManager.GetString("T341", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T35 {
            get {
                object obj = ResourceManager.GetObject("T35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They love to perch in high areas to have a panoramic view of their surroundings in order to locate their prey..
        /// </summary>
        internal static string T351 {
            get {
                return ResourceManager.GetString("T351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap T36 {
            get {
                object obj = ResourceManager.GetObject("T36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///These birds are usually related to trees such as acacia, where they usually sleep at night, since it is a very diurnal bird.
        ///.
        /// </summary>
        internal static string T361 {
            get {
                return ResourceManager.GetString("T361", resourceCulture);
            }
        }
    }
}
